Update Manager module correctly updated
sebassem/azure_arc pull request #71
Opened 2023-08-29 06:55 UTC by lloydlimmsft

2023-08-29 12:55 UTC, sebassem requested changes
Look great LLoyd , one minor comment is if you can add a section for reporting ?

2023-08-29 21:27 UTC, lloydlimmsft commented on docs/azure_arc_jumpstart/azure_arc_servers/levelup/_index.md
> +Note that all Azure VMs and Arc Server VMs are automatically enrolled in this Azure Update Management service.
No, the update manager automatically sees all Azure VMs and Arc VMs.
If you go to the portal, you can see your own jumpbox VMs in the update manager, even though you never did any enrollment other than Arc.

2023-08-29 21:27 UTC, lloydlimmsft commented
> Look great LLoyd , one minor comment is if you can add a section for reporting ?

Added.

2023-08-30 07:37 UTC, sebassem commented on docs/azure_arc_jumpstart/azure_arc_servers/levelup/_index.md
> +Note that all Azure VMs and Arc Server VMs are automatically enrolled in this Azure Update Management service.
Aaaah I misunderstood, it definitely seems them but they are not onboarded (they do not get updated automatically) , you would need to create a maintenance configuration and include those vms and arc-enabled servers. So I think for the sake of clarity we change the "automatically enrolled" wording , what do you think ?

2023-08-30 20:27 UTC, lloydlimmsft commented
Hi Seif,

I can use the words "already visible".

Thank you,
Lloyd Lim.
Call me at +6493625625<tel:+6493625625>. It rings my mobile and desk phone simultaneously.

From: Seif Bassem ***@***.***>
Sent: Wednesday, August 30, 2023 7:38 PM
To: sebassem/azure_arc ***@***.***>
Cc: Lloyd Lim ***@***.***>; Author ***@***.***>
Subject: Re: [sebassem/azure_arc] Update Manager module correctly updated (PR #71)


@sebassem commented on this pull request.

________________________________

In docs/azure_arc_jumpstart/azure_arc_servers/levelup/_index.md<https://github.com/sebassem/azure_arc/pull/71#discussion_r1309822369>:

>

-#### Task 2

+This information is taken from the link: https://azure.microsoft.com/en-us/products/azure-update-management-center

+

+This new service is currently in preview and has no powershell scripting option (as of Aug 2023)

+

+#### Prerequisites:

+Ensure that you already have your Jumpbox with VMs onboarded via Azure Arc.

+

+#### Onboarding the VMs

+Note that all Azure VMs and Arc Server VMs are automatically enrolled in this Azure Update Management service.

Aaaah I misunderstood, it definitely seems them but they are not onboarded (they do not get updated automatically) , you would need to create a maintenance configuration and include those vms and arc-enabled servers. So I think for the sake of clarity we change the "automatically enrolled" wording , what do you think ?

-
Reply to this email directly, view it on GitHub<https://github.com/sebassem/azure_arc/pull/71#discussion_r1309822369>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AR7TMH6DBYSKJBOTSQHNTSDXX3UT5ANCNFSM6AAAAAA4COQWZU>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

2023-08-31 13:13 UTC, merged