Added the change tracking module.
sebassem/azure_arc pull request #78
Opened 2023-09-07 02:56 UTC by lloydlimmsft

I still could not get it working - need someone to test that what I did is correct?

2023-09-07 10:07 UTC, sebassem commented
> I still could not get it working - need someone to test that what I did is correct?

thank you @lloydlimmsft , we want to use azure policy instead of manually enabling every machine. You would just need to assign the _(ArcBox) Enable ChangeTracking and Inventory for Arc-enabled machines_ policy on the resource group and show how to get the _arcbox-ama-ct-dcr_ resource Id and provide it in the policy. Also if you can use the dark mode in Azure that would make all screenshot consistent :)

2023-09-08 09:32 UTC, lloydlimmsft commented
Modified the screenshots to be dark instead of light now.
Please review - I've done what I could, even though it still does not work.

2023-09-10 11:33 UTC, sebassem requested changes

2023-09-10 11:33 UTC, sebassem commented on docs/azure_arc_jumpstart/azure_arc_servers/levelup/_index.md
> +Change Tracking and Inventory is an inbuilt Azure service, provided by Azure Automation. The old version uses the Log Analytics agent, while the new (preview) version uses the Azure Monitor Agent (AM
```suggestion
Change Tracking and Inventory is an built-in Azure service, provided by Azure Automation. The old version uses the Log Analytics agent, while the new (preview) version uses the Azure Monitor Agent (AMA).

```

2023-09-10 11:33 UTC, sebassem commented on docs/azure_arc_jumpstart/azure_arc_servers/levelup/_index.md
> +1. Ensure that the servers are already provisioned in Arc.
```suggestion
1. Ensure that the servers are already on-boarded to Azure Arc.

```

2023-09-10 11:33 UTC, sebassem commented on docs/azure_arc_jumpstart/azure_arc_servers/levelup/_index.md
> +2. Ensure that the AMA is already provisioned on every server.
```suggestion
2. Ensure that the Azure Monitor agent (AMA) is already deployed on every Arc-enabled server.

```

2023-09-10 11:33 UTC, sebassem commented on docs/azure_arc_jumpstart/azure_arc_servers/levelup/_index.md
>  #### Task 1
```suggestion
#### Task 1: Creating an Automation account

```

2023-09-10 11:33 UTC, sebassem commented on docs/azure_arc_jumpstart/azure_arc_servers/levelup/_index.md
> +Creating an Automation Account
```suggestion
```

2023-09-10 11:33 UTC, sebassem commented on docs/azure_arc_jumpstart/azure_arc_servers/levelup/_index.md
> +The Automation Account must also enable Change Tracking and Inventory by linking to the ArcBox Log Analytics workspace crated previously.
No need for this point as we are using Azure Policy to enable change tracking

2023-09-10 11:33 UTC, sebassem commented on docs/azure_arc_jumpstart/azure_arc_servers/levelup/_index.md
>  #### Task 2
```suggestion
#### Task 2: Enabling Change Tracking and Inventory

```

2023-09-10 11:33 UTC, sebassem commented on docs/azure_arc_jumpstart/azure_arc_servers/levelup/_index.md
> +Enabling Change Tracking and Inventory
```suggestion
```

2023-09-10 11:33 UTC, sebassem commented on docs/azure_arc_jumpstart/azure_arc_servers/levelup/_index.md
> +```note
```suggestion
>NOTE: 
```

2023-09-10 11:33 UTC, sebassem commented on docs/azure_arc_jumpstart/azure_arc_servers/levelup/_index.md
> +For Azure Arc - you must then deploy a special policy and create a Data Collection Rule (DCR) to specify the data collection characteristics.
```suggestion
>For Azure Arc - you must then deploy a special policy and create a Data Collection Rule (DCR) to specify the data collection characteristics.

```

2023-09-10 11:33 UTC, sebassem commented on docs/azure_arc_jumpstart/azure_arc_servers/levelup/_index.md
> +Follow the link here:
```suggestion
>Follow the link here:

```

2023-09-10 11:33 UTC, sebassem commented on docs/azure_arc_jumpstart/azure_arc_servers/levelup/_index.md
> +- In the Azure portal, search for the text "Preview" and for a definition type of "Initiative".
Try to use the same steps as Azure Monitor, to first search for policy then the policy itself. Don;t use this policy, instead use the one the starts with (ArcBox), this is the new policy

2023-09-10 11:33 UTC, sebassem commented on docs/azure_arc_jumpstart/azure_arc_servers/levelup/_index.md
> +az resource show --name "MSVMI-ama-vmi-default-dcr" `
This is the vminsights dcr not the change tracking one

2023-09-10 11:33 UTC, sebassem commented on docs/azure_arc_jumpstart/azure_arc_servers/levelup/_index.md
> +![Screenshot showing the policyassignment](./changetracking-assignmentid.png)
the screenshot has a red line, not sure if you meant to hide the subscription id

2023-09-10 11:33 UTC, sebassem commented on docs/azure_arc_jumpstart/azure_arc_servers/levelup/_index.md
> +#### Task 3
```suggestion
#### Task 3: Using Change Tracking

```

2023-09-10 11:33 UTC, sebassem commented on docs/azure_arc_jumpstart/azure_arc_servers/levelup/_index.md
> +Using Change Tracking
```suggestion
```

2023-09-11 05:00 UTC, lloydlimmsft commented on docs/azure_arc_jumpstart/azure_arc_servers/levelup/_index.md
> +![Screenshot showing the policyassignment](./changetracking-assignmentid.png)
That is for the az command on the next part - to programmaically create remediation tasks for the policies.

2023-09-11 07:31 UTC, merged